
- name: Modify NFS exports
  lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item }}"
  with_items:
    - '"{{ nfsshare }}" Node*(rw,no_root_squash,no_subtree_check,insecure)'


- name: Reload NFS exports
  ansible.builtin.systemd:
    daemon_reload: yes
    state: started
    name: "{{ servicename }}"

  notify: 
    - restart nfs-server
